# Generated by Django 5.2.5 on 2025-08-31 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('internal_id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('ratings_data', models.JSONField(blank=True, default=list)),
                ('avg_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Point of Interest',
                'verbose_name_plural': 'Points of Interest',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['external_id'], name='poi_pointof_externa_68209e_idx'), models.Index(fields=['category'], name='poi_pointof_categor_5f009d_idx'), models.Index(fields=['avg_rating'], name='poi_pointof_avg_rat_6fba2f_idx')],
            },
        ),
    ]
