name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: poi_user
          POSTGRES_PASSWORD: poi_pass
          POSTGRES_DB: poi_test_db
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DJANGO_SETTINGS_MODULE: poi_project.settings
      PYTHONUNBUFFERED: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || pip install django

      - name: Run migrations
        run: python manage.py migrate

      - name: Run tests
        run: python manage.py test

  docker-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image with Compose
        run: docker compose build

      - name: Run Django tests inside Docker
        # Overrides the service command to run tests in the built container
        run: docker compose run --rm web python manage.py test

      - name: Teardown
        if: always()
        run: docker compose down -v